### ISSUE TITLE
Search results don't get cleared after pressing `ESC`.

### ISSUE THREAD

**Issue by khaledkee** [thabetx/boarda-release#2]
When I search for something, it highlights matched cards (The highlight is different from the one using `b` key). After I find the card, I would then need that highlight to be removed and expected that `ESC` would remove the highlight but it now `release 23.12.25` requires entering search again and press enter key. Also this part might be confusing because the old search keyword is still written so I first guessed that I had to delete it but it was written in gray so I understood the text field is empty.

**Comment by thabetx** [comment]
Yes it might not be that clear. But making 'esc' functional helps a bit here. So escape will clear the search in the next release. Thanks for the feedback.
