### ISSUE TITLE
Shortcuts Problems

### ISSUE THREAD

**Issue by Bravewarrior0** [thabetx/boarda-release#5]
**Undo-Redo shortcuts:**
The tutorial mentioned
`'ctrl-z' to undo, 'ctrl-z' or ctrl+shift+z' to redo`
I think there is a typo, it should be corrected to:
`'ctrl+z' to undo, 'ctrl+y' or ctrl+shift+z' to redo`

**Copy shortcut:**
I tried `ctrl+c` for copy as mentioned by tutorial but it creates a `new column` instead

**Comment by thabetx** [comment]
Both are fixed now and will be available on next release. Thank you.
