### ISSUE TITLE
Feature request: Support Creating new column to the left

### ISSUE THREAD

**Issue by Bravewarrior0** [thabetx/boarda-release#6]
I had a column at the beginning of the board and I deleted it, then after a while I was trying to add a new one at the beginning but I don't have a way to do that, so I think it will be a nice feature to support adding a new column on the left using **shift+c** or something similar.

**Comment by thabetx** [comment]
Thanks for the suggestion. shift+c will add a column to the left on the next release. You can also move columns left or right after creation by shift+left/right (like cards) but you must be selection the header.

The tutorial is not clear about that. I will update it.
